version: '3.8'

services:
  bitbotby:
    build: .
    env_file:
      - .env
    volumes:
      - ./models:/app/models  # Монтируем директорию моделей
    command: python run_bot.py --strategy ppo
    restart: unless-stopped
